name: Run Google Colab Notebook

on:
  schedule:
    - cron: '0 * * * *' # 毎時実行
  push:
    branches:
      - main # main ブランチに push されたときにも実行

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-httplib2 google-auth-oauthlib google-api-python-client
          pip install jupyter nbconvert

      - name: Convert and run notebook
        run: |
          jupyter nbconvert --to python FourM_scraping.ipynb
          python FourM_scraping.py
