name: Auto Run Colab Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout specific repository
      uses: actions/checkout@v3
      with:
        repository: tt-naver/FourM_scraping
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install nbconvert
        pip install pandas google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: List repository files
      run: ls -l

    - name: Convert Notebook to Script
      run: |
        if [ -f FourM_scraping.ipynb ]; then
          echo "Found FourM_scraping.ipynb"
          jupyter nbconvert --to script FourM_scraping.ipynb
        else
          echo "Error: FourM_scraping.ipynb not found"
          exit 1
        fi

    - name: List directory after conversion
      run: ls -l

    - name: Debug:Verify Python Script
      run: |
        if [ -f FourM_scraping.py ]; then
          echo "Python script found"
        else
          echo "Error: FourM_scraping.py not found"
          exit 1
        fi

    - name: Clean Python Script
      run: |
        sed -i '/get_ipython/d' FourM_scraping.py
        sed -i '/^!/d' FourM_scraping.py

    - name: Set up Google credentials
      run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > /tmp/google-credentials.json

    - name: Run Python Script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /content/opportune-ruler-347802-94d5a92e419d.json
      run: python FourM_scraping.py
