name: 自動実行Colabノートブック

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # シークレットを環境変数に設定

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v3

    - name: Pythonのセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 依存関係をインストール
      run: |
        pip install nbconvert
        pip install pandas
        pip install google-auth google-auth-httplib2 google-auth-oauthlib google-api-python-client

    - name: スクリプトの存在を確認
      run: |
        ls -l  # カレントディレクトリのファイルをリストして、スクリプトが存在するか確認

    - name: Pythonスクリプトを実行する
      run: |
        echo "FourM_scraping.py を実行しています"
        # スクリプトがサブディレクトリにある場合は、以下のように適切なパスを指定
        python ./FourM_scraping/FourM_scraping.py
