name: Auto Run Colab Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install nbconvert

    - name: Convert Notebook to Script
      run: |
        if [ -f FourM_scraping.ipynb ]; then
          jupyter nbconvert --to script FourM_scraping.ipynb
        else
          echo "Error: FourM_scraping.ipynb not found"
          exit 1
        fi

    - name: Debug:List Current Directory
      run: ls -l

    - name: Debug:Verify Python Script
      run: |
        if [ -f FourM_scraping.py ]; then
          echo "Python script found"
        else
          echo "Error: FourM_scraping.py not found"
          exit 1
        fi

    - name: Clean Python Script
      run: |
        sed -i '/get_ipython/d' FourM_scraping.py
        sed -i '/^!/d' FourM_scraping.py

    - name: Run Python Script
      run: python FourM_scraping.py
